finish
Sergey4857/nodejs-rest-api pull request #3
Opened 2023-09-21 10:12 UTC by Sergey4857

2023-09-21 16:48 UTC, KhYulian commented on middlewarees/authenticate.js
> +  if (bearer !== "Bearer") {
```suggestion
  if (bearer !== "Bearer" || !token) {
```

2023-09-21 16:48 UTC, KhYulian commented on routes/api/auth.js
> +// ---------------------register------------------------
це зайве

2023-09-21 16:49 UTC, KhYulian commented on routes/api/auth.js
> +const ctrl = require("../../controller/auth");
зробіть деструктуризацію

2023-09-21 16:49 UTC, KhYulian commented on service/joi-schemas/subscriptionSchemaJoi.js
> +const SomeMyEnum = {
```suggestion
const SubscriptionTypes = {
```

2023-09-21 16:49 UTC, KhYulian commented on service/joi-schemas/updateSchemaJoi.js
> +const SchemaForUpdateJoi = Joi.object({
```suggestion
const schemaForUpdateJoi = Joi.object({
```

2023-09-21 16:49 UTC, KhYulian requested changes
залишив коменти

2023-09-21 20:11 UTC, Sergey4857 commented
Якщо все правильно зрозумів, пофіксив вказане у коміті fix

2023-09-22 06:17 UTC, KhYulian approved these changes

2023-09-22 06:17 UTC, merged